function get_nav_language(){var nav_lng;if(navigator.userlanguage)nav_lng=navigator.userlanguage;if(navigator.browserLanguage)nav_lng=navigator.browserLanguage;if(navigator.systemLanguage)nav_lng=navigator.systemLanguage;if(navigator.language)nav_lng=navigator.language;return nav_lng.toLowerCase();}
var coolplayer_nav_lng=get_nav_language();var coolplayer_nav_language="en, zh-cn";if(coolplayer_nav_language.indexOf(coolplayer_nav_lng)==-1)coolplayer_nav_lng='en';var coolplayer_lang=[];coolplayer_lang['en']=[];coolplayer_lang['en']['loading']="Loading...";coolplayer_lang['en']['rpcnotready']="Cool Player RPC is not ready.";coolplayer_lang['en']['notsupport']="This media can NOT be support to embed into the page, <br />but you can download it by the following link.";coolplayer_lang['en']['waiting']="Wait a moment, please!";coolplayer_lang['en']['url']="URL:";coolplayer_lang['zh-cn']=[];coolplayer_lang['zh-cn']['loading']="&#36733;&#20837;&#20013;&#8230;&#8230;";coolplayer_lang['zh-cn']['rpcnotready']="Cool Player &#36828;&#31243;&#36807;&#31243;&#35843;&#29992;&#23578;&#26410;&#23601;&#32490;&#12290;";coolplayer_lang['zh-cn']['notsupport']="&#35813;&#23186;&#20307;&#19981;&#25903;&#25345;&#22312;&#39029;&#38754;&#20869;&#23884;&#20837;&#26174;&#31034;&#65292;<br />&#20294;&#20320;&#21487;&#20197;&#36890;&#36807;&#19979;&#38754;&#30340;&#36830;&#25509;&#19979;&#36733;&#23427;&#12290;";coolplayer_lang['zh-cn']['waiting']="&#35831;&#31245;&#21518;&#65281;";coolplayer_lang['zh-cn']['url']="&#22320;&#22336;&#65306;";function load_coolplayer(url,id,width,height,autoplay,loop,charset){if(coolplayer_rpc.ready){window.setTimeout(["coolplayer('",[url,id,width,height,autoplay,loop,charset].join("', '"),"');"].join(''),100);}
else{window.setTimeout(["load_coolplayer('",[url,id,width,height,autoplay,loop,charset].join("', '"),"');"].join(''),100);}}
function coolplayer(url,id,width,height,autoplay,loop,charset){if(coolplayer_rpc.ready){var result=['<span class="coolplayer_info" style="width: ',(parseInt(width)-2),'px; border-top: 0; border-bottom: 0; padding: 12px 0;">',coolplayer_lang[coolplayer_nav_lng]['loading'],'</span>'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=coolplayer_lang[coolplayer_nav_lng]['waiting'];coolplayer_rpc.play_media(url,id,width,height,autoplay,loop,charset);}
else{alert(coolplayer_lang[coolplayer_nav_lng]['rpcnotready']);}}
function coolplayer_flash(id,src,mime,width,height,autoplay,loop,url,info){var result=['<![if !IE]><object data="',src,'" type="',mime,'" ','width="',width,'" height="',height,'" class="coolplayer_moz">','<param name="play" value="',autoplay,'" />','<param name="loop" value="',loop,'" />','<param name="wmode" value="opaque" />','<param name="quality" value="high" /></object><![endif]>','<!--[if IE]><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ','width="',width,'" height="',height,'">','<param name="movie" value="',src,'" />','<param name="play" value="',autoplay,'" />','<param name="loop" value="',loop,'" />','<param name="wmode" value="opaque" />','<param name="quality" value="high" />','</object><![endif]-->'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=['<a href="',url,'">',info,'</a>'].join('');}
function coolplayer_qt(id,src,mime,width,height,autoplay,loop,url,info){var result=['<![if !IE]><object data="',src,'" type="',mime,'" ','width="',width,'" height="',height,'" class="coolplayer_moz">','<param name="autoplay" value="',autoplay,'" />','<param name="loop" value="',loop,'" /></object><![endif]>','<!--[if IE]><object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" ','width="',width,'" height="',height,'">','<param name="autoplay" value="',autoplay,'" />','<param name="loop" value="',loop,'" />','<param name="src" value="',src,'" />','</object><![endif]-->'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=['<a href="',url,'">',info,'</a>'].join('');}
function coolplayer_rm(id,src,mime,width,height,autoplay,loop,url,info){var result=['<object classid="clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA" ','width="',width,'" height="',height,'">','<param name="src" value="',src,'" />','<param name="controls" value="Imagewindow" />','<param name="console" value="clip',id,'" />','<param name="autostart" value="',autoplay,'" />','<param name="loop" value="',loop,'" />','<embed src="',src,'" type="audio/x-pn-realaudio-plugin" ','autostart="',autoplay,'" loop="',loop,'" console="clip',id,'" ','width="',width,'" height="',height,'" ','controls="Imagewindow"></embed><br />','</object>','<object classid="clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA" ','width="',width,'" height="42">','<param name="src" value="',src,'" />','<param name="controls" value="ControlPanel" />','<param name="console" value="clip',id,'" />','<param name="autostart" value="',autoplay,'" />','<param name="loop" value="',loop,'" />','<embed src="',src,'" type="audio/x-pn-realaudio-plugin" ','autostart="',autoplay,'" loop="',loop,'" console="clip',id,'" ','width="',width,'" height="42" ','controls="ControlPanel"></embed>','</object>'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=['<a href="',url,'">',info,'</a>'].join('');}
function coolplayer_wm(id,src,mime,width,height,autoplay,loop,url,info){var result=['<![if !IE]><object data="',src,'" type="',mime,'" ','width="',width,'" height="',height,'" class="coolplayer_moz">','<param name="autoplay" value="',autoplay,'" />','<param name="autostart" value="',autoplay,'" />','<param name="loop" value="',loop,'" /></object><![endif]>','<!--[if IE]><object classid="clsid:22D6F312-B0F6-11D0-94AB-0080C74C7E95" ','width="',width,'" height="',height,'">','<param name="autoplay" value="',autoplay,'" />','<param name="autostart" value="',autoplay,'" />','<param name="loop" value="',loop,'" />','<param name="filename" value="',src,'" />','</object><![endif]-->'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=['<a href="',url,'">',info,'</a>'].join('');}
function coolplayer_pdf(id,src,mime,width,height,autoplay,loop,url,info){var result=['<![if !IE]><object data="',src,'" type="',mime,'" ','width="',width,'" height="',height,'" class="coolplayer_moz">','</object><![endif]>','<!--[if IE]><object classid="clsid:CA8A9780-280D-11CF-A24D-444553540000" ','width="',width,'" height="',height,'">','<param name="src" value="',src,'" />','</object><![endif]-->'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=['<a href="',url,'">',info,'</a>'].join('');}
function coolplayer_img(id,src,mime,width,height,autoplay,loop,url,info){var result=['<img src="',src,'" style="width: ',width,'px; height: ',height,'px" alt="" />'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=['<a href="',url,'">',info,'</a>'].join('');}
function coolplayer_unknown(id,src,mime,width,height,autoplay,loop,url,info){var result=['<span class="coolplayer_info" style="width: ',(parseInt(width)-2),'px; border-top: 0; border-bottom: 0; padding: 12px 0;">',coolplayer_lang[coolplayer_nav_lng]['notsupport'],'</span>'].join('');document.getElementById('coolplayer_container_'+id).innerHTML=result;document.getElementById('coolplayer_info_'+id).innerHTML=['<a href="',url,'">',info,'</a>'].join('');}
function coolplayer_input(e,width,height,autoplay,loop,charset){var id=e.id.substr(16);var old_content=e.innerHTML;e.innerHTML=coolplayer_lang[coolplayer_nav_lng]['url'];var input=document.createElement('input');input.type="text";input.style.width=(width-60)+"px";input.onkeypress=function(event){if(window.event)event=window.event;if(event.keyCode==27){this.blur();}
if(event.keyCode==13){coolplayer(this.value,id,width,height,autoplay,loop,charset);}}
input.onblur=function(){e.innerHTML=old_content;}
e.appendChild(input);input.select();}
phprpc_client.create('coolplayer_rpc');coolplayer_rpc.use_service('http://www.coolcode.cn/wp-content/plugins/coolplayer/rpc.php');coolplayer_rpc.play_media_callback=function(result,args,output){if(result instanceof phprpc_error){alert(result.errstr);}
else{var str;str=[result['func'],"('",[result['id'],result['src'],result['mime'],result['width'],result['height'],result['autoplay'],result['loop'],result['url'],result['info']].join("', '"),"');"].join('');eval(str);}}
function FlashRequest(status,args){void(0);}